EXCLUDE:
  W_had: &W_had
    q1: null
    q2: null
    SYMMETRY: [ q1, q2 ]

  W_lep: &W_lep
    l: null
  #    v: null

  Z_had: &Z_had
    q1: null
    q2: null
    SYMMETRY: [ q1, q2 ]

  Z_lep: &Z_lep
    l1: null
    l2: null
    SYMMETRY: [ l1, l2 ]

  top_had: &top_had
    b: null
    W: *W_had

  top_lep: &top_lep
    b: null
    W: *W_lep

  a_had: &a_had
    b1: null
    b2: null
    SYMMETRY: [ b1, b2 ]

QCD:
  category: QCD
  process_id: 0
  diagram: { }

QCD_2b:
  category: QCD
  process_id: 0
  diagram: { }

QCD_2b2j:
  category: QCD
  process_id: 0
  diagram: { }

QCD_4b:
  category: QCD
  process_id: 0
  diagram: { }

TTHadronics:
  category: TT
  process_id: 1
  diagram: &TTHadronics
    t1: *top_had
    t2: *top_had
    SYMMETRY: [ t1, t2 ]

TTHadronics_mlm:
  category: TT
  process_id: 1
  diagram: *TTHadronics

TT1L:
  category: TT
  process_id: 1
  diagram: &TT1L
    t1: *top_had
    t2: *top_lep

TT1L_mlm:
  category: TT
  process_id: 1
  diagram: *TT1L

TT2L:
  category: TT
  process_id: 1
  diagram: &TT2L
    t1:
      b: null
      W:
        l+: null
        v: null
    t2:
      b: null
      W:
        l-: null
        v: null

TT2L_mlm:
  category: TT
  process_id: 1
  diagram: *TT2L

ttW_FullHadronics:
  category: ttW
  process_id: 2
  diagram:
    t1: *top_had
    t2: *top_had
    W: *W_had
    SYMMETRY: [ t1, t2 ]

ttZ_FullHadronics:
  category: ttZ
  process_id: 3
  diagram:
    t1: *top_had
    t2: *top_had
    Z: *Z_had
    SYMMETRY: [ t1, t2 ]

ttZ_Leptonic:
  category: ttZ
  process_id: 3
  diagram:
    t1: *top_had
    t2: *top_had
    Z: *Z_lep
    SYMMETRY: [ t1, t2 ]

WJetsToQQ:
  category: WJets
  process_id: 4
  diagram:
    W: *W_had

WJetsToLNu:
  category: WJets
  process_id: 4
  diagram:
    W: *W_lep

ZJetsToQQ:
  category: ZJets
  process_id: 5
  diagram:
    Z: *Z_had

ZJetsToLL:
  category: ZJets
  process_id: 5
  diagram:
    Z: *Z_lep

WW_1L:
  category: WW
  process_id: 6
  diagram:
    W1: *W_lep
    W2: *W_had

WW_2L:
  category: WW
  process_id: 6
  diagram:
    W1: *W_lep
    W2: *W_lep
    SYMMETRY: [ W1, W2 ]

ZZ_4L:
  category: ZZ
  process_id: 7
  diagram:
    Z1: *Z_lep
    Z2: *Z_lep
    SYMMETRY: [ Z1, Z2 ]

ZZ_2L:
  category: ZZ
  process_id: 7
  diagram:
    Z1: *Z_lep
    Z2: *Z_had

WZ_1L:
  category: WZ
  process_id: 8
  diagram:
    W: *W_lep
    Z: *Z_had

WZ_2L:
  category: WZ
  process_id: 8
  diagram:
    W: *W_had
    Z: *Z_lep

WZ_3L:
  category: WZ
  process_id: 8
  diagram:
    W: *W_lep
    Z: *Z_lep

haa_ma20:
  category: haa
  process_id: 9
  diagram:
    H:
      a1: *a_had
      a2: *a_had
      SYMMETRY: [ a1, a2 ]
  store_full_name: true

haa_ma30:
  category: haa
  process_id: 9
  diagram:
    H:
      a1: *a_had
      a2: *a_had
      SYMMETRY: [ a1, a2 ]
  store_full_name: true

haa_ma40:
  category: haa
  process_id: 9
  diagram:
    H:
      a1: *a_had
      a2: *a_had
      SYMMETRY: [ a1, a2 ]
  store_full_name: true

haa_ma60:
  category: haa
  process_id: 9
  diagram:
    H:
      a1: *a_had
      a2: *a_had
      SYMMETRY: [ a1, a2 ]
  store_full_name: true

Zjets_m300:
  category: ZJets
  process_id: 5
  diagram:
    Z: *Z_had