platform:
  data_parquet_dir: cache/data
  number_of_workers: 1
  resources_per_worker:
    CPU: 1
    GPU: 1
  batch_size: 4
  prefetch_batches: 1
  use_gpu: true
logger:
  wandb:
    project: EveNet
    run_name: Pretrain
    tags:
    - EveNet
    simplified: false
  local:
    save_dir: cache/log
    name: Pretrain
    version: v1
options:
  default: options/options.yaml
  Training:
    total_epochs: 50
    epochs: 10
    model_checkpoint_save_path: cache/checkpoint
    model_checkpoint_load_path: null
    pretrain_model_load_path: /Users/xuliang/.cache/huggingface/hub/models--Avencast--EveNet/snapshots/3969201ae20b5353ddb99c1810254ea7115217ed/checkpoints.20M.a4.last.ckpt
    diffusion_every_n_epochs: 4
    diffusion_every_n_steps: 1
    eval_metrics_every_n_epochs: 1
    Components:
      Classification:
        include: true
      Regression:
        include: false
      Assignment:
        include: false
      Segmentation:
        include: false
        use_full_mask: true
      GlobalGeneration:
        include: false
        diffusion_steps: 2
      ReconGeneration:
        include: true
        diffusion_steps: 2
      TruthGeneration:
        include: true
        diffusion_steps: 2
    EarlyStopping:
      patience: 100
      min_delta: 0.0
      monitor: lr-body
      mode: min
      verbose: true
    EMA:
      enable: true
      decay: 0.999
      start_epoch: 0
      update_every_n_steps: 1
      replace_model_after_load: true
      replace_model_at_end: false
  Dataset:
    dataset_limit: 1.0
    normalization_file: cache/data/normalization.pt
    val_split:
    - 0.95
    - 1.0
network:
  default: network/network-20M.yaml
  Body:
    PET:
      feature_drop: 0.0
  ReconGeneration:
    feature_drop: 0.0
  TruthGeneration:
    feature_drop: 0.0
event_info:
  default: event_info/multi_process.yaml
resonance:
  default: resonance/standard_model.yaml
